name: Deploy Project
# adding multiple triggers to workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install project dependencies
        # uses versions of the packages in the locked versions - safe
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install project dependencies
        # uses versions of the packages in the locked versions - safe
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo 'DEPLOYING....'
